
version: "3.9"

services:
  db:
    container_name: sql
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "Admin!Password1"
      ACCEPT_EULA: "Y"

  server:
    container_name: server
    build: .
    ports:
      - "8412:80"
    depends_on:
      - db
